export interface Certificate {
  id: number;
  title: string;
  issuer: string;
  date: string;
  category: string;
  description: string;
  credentialId?: string;
  url?: string;
  logoId: number;
  certExt: string;
  hasCert: boolean;
}

// File extension for each logo by its ID
export const logoExtMap: Record<number, string> = {
  1: 'webp', 2: 'png', 3: 'png', 4: 'png', 5: 'png',
  6: 'jpg',  8: 'jpg', 13: 'jpg', 14: 'jpg', 19: 'jpg',
  20: 'jpg', 24: 'jpg', 27: 'jpg', 28: 'jpg', 30: 'jpg',
  32: 'jpg', 40: 'jpg', 43: 'jpg', 45: 'jpg', 47: 'jpg',
  50: 'jpg', 51: 'jpg', 53: 'jpg', 58: 'jpg', 71: 'jpg',
  74: 'jpg', 79: 'jpg', 81: 'jpg', 83: 'jpg', 97: 'jpg',
};

export function certImagePath(id: number, ext: string): string {
  return `/api/assets/Certificates/${id}.${ext}`;
}

export function logoImagePath(logoId: number): string {
  return `/api/assets/Logos/${logoId}.${logoExtMap[logoId] ?? 'jpg'}`;
}

export const categories = ['All', 'AI / ML', 'Cloud', 'Data', 'Web Dev', 'DevOps', 'Industry Sim'];

export const categoryGradients: Record<string, string> = {
  'AI / ML':       'linear-gradient(135deg, #0d0b1a 0%, #20103a 50%, #0d0820 100%)',
  'Cloud':         'linear-gradient(135deg, #060f1a 0%, #0d1e35 50%, #050c18 100%)',
  'Data':          'linear-gradient(135deg, #051510 0%, #092515 50%, #030e08 100%)',
  'Web Dev':       'linear-gradient(135deg, #1a0608 0%, #2a0d0e 50%, #120405 100%)',
  'DevOps':        'linear-gradient(135deg, #080d18 0%, #101828 50%, #050a12 100%)',
  'Industry Sim':  'linear-gradient(135deg, #1a1005 0%, #2e1c0a 50%, #12100a 100%)',
};

export const certificates: Certificate[] = [
  {
    id: 1, title: 'Foundations of Data Science', issuer: 'Analytics Vidhya',
    date: 'Dec 2025', category: 'AI / ML',
    description: 'Foundational data science course covering statistical analysis, data preprocessing, exploratory data analysis, and building predictive models with Python.',
    credentialId: 'yfrnbi2aka',
    url: 'https://courses.analyticsvidhya.com/certificates/yfrnbi2aka',
    logoId: 1, certExt: 'jpg', hasCert: true,
  },
  {
    id: 2, title: 'Gemini Certified Educator', issuer: 'Google for Education',
    date: 'Nov 2025', category: 'AI / ML',
    description: "Validates proficiency in Google's Gemini AI tools for education — covering AI-assisted lesson planning, personalized learning, and classroom productivity workflows.",
    credentialId: '167837476',
    url: 'https://edu.google.accredible.com/c0b7921d-813c-4bdb-85c1-3533a6c1f2a9#acc.0BCdzWcD',
    logoId: 2, certExt: 'jpg', hasCert: true,
  },
  {
    id: 3, title: 'Academy Accreditation – Generative AI Fundamentals', issuer: 'Databricks',
    date: 'Sep 2024', category: 'AI / ML',
    description: 'Covers generative AI fundamentals including LLMs, prompt engineering, and deploying responsible AI models within the Databricks Lakehouse platform.',
    credentialId: '115850728',
    url: 'https://credentials.databricks.com/8e79f17c-f4ef-431f-9ad4-66943973977e',
    logoId: 3, certExt: 'png', hasCert: true,
  },
  {
    id: 4, title: 'Fundamentals of Digital Marketing', issuer: 'Google',
    date: 'Nov 2025', category: 'Web Dev',
    description: 'Google-accredited digital marketing course covering SEO, SEM, social media marketing, content strategy, and analytics for building effective online campaigns.',
    url: 'https://skillshop.exceedlms.com/student/award/rqMymjrHJ3evEx9L2ifyg5oZ',
    logoId: 4, certExt: 'jpg', hasCert: true,
  },
  {
    id: 5, title: 'Introduction to Generative AI Studio', issuer: 'SkillUp Online',
    date: 'Nov 2025', category: 'AI / ML',
    description: "Hands-on introduction to Google Cloud's Generative AI Studio for building, evaluating, and deploying LLM-powered applications on Vertex AI.",
    url: 'https://www.simplilearn.com/skillup-certificate-landing?token=eyJjb3Vyc2VfaWQiOiIzODE0IiwiY2VydGlmaWNhdGVfdXJsIjoiaHR0cHM6XC9cL2NlcnRpZmljYXRlcy5zaW1wbGljZG4ubmV0XC9zaGFyZVwvOTQ0ODIzM181NjU1NzIyMTc2Mzc4Nzc0MTg0My5wbmciLCJ1c2VybmFtZSI6IlJpc2hhYmggU2hhcm1hIn0%3D&utm_source=shared-certificate&utm_medium=lms&utm_campaign=shared-certificate-promotion',
    logoId: 5, certExt: 'png', hasCert: true,
  },
  {
    id: 6, title: 'Oracle Cloud Infrastructure 2025 Certified DevOps Professional', issuer: 'Oracle',
    date: 'Sep 2025', category: 'DevOps',
    description: 'Comprehensive OCI DevOps training covering application development, testing, security, and seamless deployment using Oracle Cloud Infrastructure DevOps services.',
    url: 'https://catalog-education.oracle.com/ords/certview/sharebadge?id=4AE336D19912A5EEB0AC2D386E39CCA4F66BE4E323A46B459393D03D4CA279C0',
    logoId: 6, certExt: 'jpg', hasCert: true,
  },
  {
    id: 7, title: 'Oracle Cloud Infrastructure 2025 Certified Data Science Professional', issuer: 'Oracle',
    date: 'Aug 2025', category: 'AI / ML',
    description: 'Validates expertise in building data science solutions and managing the complete ML lifecycle on OCI, including the OCI Data Science service and ML best practices.',
    url: 'https://catalog-education.oracle.com/ords/certview/sharebadge?id=4AE336D19912A5EEB0AC2D386E39CCA4C53B4166A30E8866580A647FF280384B',
    logoId: 6, certExt: 'jpg', hasCert: true,
  },
  {
    id: 8, title: 'Enterprise Design Thinking Practitioner', issuer: 'IBM',
    date: 'Aug 2025', category: 'Industry Sim',
    description: 'IBM-certified practitioner credential validating proficiency in Enterprise Design Thinking for solving complex business challenges with a human-centered collaborative approach.',
    url: 'https://www.credly.com/badges/7aa39d37-ae0c-4aa2-a2e4-a7f5523c135f/public_url',
    logoId: 8, certExt: 'png', hasCert: true,
  },
  {
    id: 9, title: 'Explore Emerging Tech', issuer: 'IBM',
    date: 'Aug 2025', category: 'Industry Sim',
    description: 'Broad overview of emerging technologies including AI, blockchain, quantum computing, IoT, and cloud — covering their business implications and transformative potential.',
    url: 'https://www.credly.com/badges/2625b831-e563-4729-ad25-49f2186c897d/public_url',
    logoId: 8, certExt: 'jpg', hasCert: true,
  },
  {
    id: 10, title: 'Oracle Cloud Infrastructure 2025 Certified Generative AI Professional', issuer: 'Oracle',
    date: 'Aug 2025', category: 'AI / ML',
    description: 'Validates deep expertise in Oracle Cloud Generative AI services including LLMs, RAG, Semantic Search, vector databases, and LangChain for building production AI applications.',
    url: 'https://catalog-education.oracle.com/ords/certview/sharebadge?id=FB62C151A6A725BF58FDC652AF3F15FE02FCE228B0BD345E592D200FEEA53DF8',
    logoId: 6, certExt: 'png', hasCert: true,
  },
  {
    id: 11, title: 'Oracle AI Vector Search Certified Professional', issuer: 'Oracle',
    date: 'Aug 2025', category: 'AI / ML',
    description: 'Certification for Oracle DBAs and AI engineers covering vector data storage, semantic/similarity search, embeddings, and building RAG applications using Oracle AI Database.',
    url: 'https://catalog-education.oracle.com/ords/certview/sharebadge?id=6857ADF19D358841B070C9EC6140FA6D1754A2D9E4AF62AE384C0412227BA820',
    logoId: 6, certExt: 'jpg', hasCert: true,
  },
  {
    id: 12, title: 'Oracle Cloud Infrastructure 2025 Certified AI Foundations Associate', issuer: 'Oracle',
    date: 'Aug 2025', category: 'AI / ML',
    description: 'Foundational OCI AI certification introducing AI/ML concepts, Oracle Cloud AI services, and practical ML application within the Oracle Cloud Infrastructure.',
    url: 'https://catalog-education.oracle.com/ords/certview/sharebadge?id=40A9F1178C0A4517FF53CE4782A203CA076473842E9AFF33E20B5C3B0745DF71',
    logoId: 6, certExt: 'jpg', hasCert: true,
  },
  {
    id: 13, title: 'Machine Learning Terminology and Processes', issuer: 'Amazon Web Services (AWS)',
    date: 'Aug 2025', category: 'AI / ML',
    description: 'Core machine learning terminology, workflows, and foundational concepts in the AWS ecosystem, including supervised/unsupervised learning and the AWS ML service stack.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 14, title: 'TCS iON Career Edge – Young Professional', issuer: 'TCS iON',
    date: 'Aug 2025', category: 'Industry Sim',
    description: 'TCS iON career readiness program covering communication skills, business etiquette, problem-solving frameworks, and professional workplace skills for corporate career entry.',
    logoId: 14, certExt: 'jpg', hasCert: true,
  },
  {
    id: 15, title: 'AWS Cloud Essentials', issuer: 'Amazon Web Services (AWS)',
    date: 'Aug 2025', category: 'Cloud',
    description: 'Earners have developed knowledge of foundational AWS Cloud concepts focusing on Compute, Storage, Networking, and Database services, security, architecture, pricing, and support.',
    url: 'https://www.credly.com/badges/e441debe-c05a-4337-88cc-a238ecd921b0/public_url',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 16, title: 'AWS Billing and Cost Management', issuer: 'Amazon Web Services (AWS)',
    date: 'Aug 2025', category: 'Cloud',
    description: 'In-depth coverage of AWS billing tools, cost optimization strategies, and cloud financial management including Cost Explorer, Budgets, Cost Allocation Tags, and Reserved Instances.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 17, title: 'Getting Started with AWS Cloud Acquisition', issuer: 'Amazon Web Services (AWS)',
    date: 'Aug 2025', category: 'Cloud',
    description: 'Introductory course on procurement, acquisition frameworks, and compliance processes for adopting AWS cloud services within enterprise and government organizations.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 18, title: 'Getting Started with AWS Cloud Essentials', issuer: 'Amazon Web Services (AWS)',
    date: 'Aug 2025', category: 'Cloud',
    description: 'Foundational overview of cloud computing concepts and core AWS services including compute, storage, networking, and databases for building cloud literacy.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 19, title: 'DAX in Power BI', issuer: 'Cambridge International Qualifications, UK',
    date: 'Jul 2025', category: 'Data',
    description: 'Deep dive into Data Analysis Expressions (DAX) for creating advanced calculated measures, time intelligence functions, and optimizing analytical models in Microsoft Power BI.',
    url: 'https://docs.uniathena.com/prod/course/certificate/629_1753789188_certificate.jpg',
    logoId: 19, certExt: 'jpg', hasCert: true,
  },
  {
    id: 20, title: 'Python Essentials', issuer: 'Cisco',
    date: 'Jul 2025', category: 'Web Dev',
    description: 'Cisco and OpenEDG Python Institute verify successful completion of Python Essentials 1 — covering syntax, semantics, data structures, and core programming concepts.',
    url: 'https://www.credly.com/badges/b2f93e91-05b5-40c7-8cf8-41e475e5e1c9/public_url',
    logoId: 20, certExt: 'jpg', hasCert: true,
  },
  {
    id: 21, title: 'Basics of Psychology – Approaches & Methodology', issuer: 'Cambridge International Qualifications, UK',
    date: 'Jul 2025', category: 'Industry Sim',
    description: 'Introduction to psychological research methods and foundational concepts covering biological, cognitive, behavioral, and sociocultural perspectives in psychology.',
    url: 'https://docs.uniathena.com/prod/course/certificate/765_1753672679_certificate.jpg',
    logoId: 19, certExt: 'jpg', hasCert: true,
  },
  {
    id: 22, title: 'Basics of Microsoft Power BI', issuer: 'Cambridge International Qualifications, UK',
    date: 'Jul 2025', category: 'Data',
    description: 'Foundational Power BI certification covering data import, Power Query transformations, building interactive dashboards, and sharing business intelligence reports.',
    url: 'https://docs.uniathena.com/prod/course/certificate/625_1753672635_certificate.jpg',
    logoId: 19, certExt: 'jpg', hasCert: true,
  },
  {
    id: 23, title: 'Cyber Security', issuer: 'Cisco',
    date: 'Jul 2025', category: 'Web Dev',
    description: 'Cisco-verified Introduction to Cybersecurity covering global cyber threats, vulnerability detection, defense strategies, and career pathways in cybersecurity.',
    url: 'https://www.credly.com/badges/e1a5de87-c482-459e-9ef5-65b44423ca17/public_url',
    logoId: 20, certExt: 'jpg', hasCert: true,
  },
  {
    id: 24, title: 'Master ChatGPT', issuer: 'UniAthena',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Practical guide to mastering ChatGPT for productivity, content creation, coding assistance, and professional workflows using advanced prompting techniques.',
    url: 'https://docs.uniathena.com/prod/course/certificate/810_1753014946_certificate.jpg',
    logoId: 24, certExt: 'jpg', hasCert: true,
  },
  {
    id: 25, title: 'Machine Learning', issuer: 'Cambridge International Qualifications, UK',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Comprehensive machine learning course covering regression, classification, clustering, neural networks, model evaluation, and practical ML application development.',
    url: 'https://docs.uniathena.com/prod/course/certificate/322_1752990215_certificate.jpg',
    logoId: 19, certExt: 'jpg', hasCert: true,
  },
  {
    id: 26, title: 'Pandas for Data Analysis in Python', issuer: 'Analytics Vidhya',
    date: 'Jul 2025', category: 'Data',
    description: 'Hands-on Pandas mastery for data manipulation, cleaning, transformation, groupby operations, merging, and working with real-world datasets in Python.',
    url: 'https://courses.analyticsvidhya.com/certificates/qcxjkaatqa',
    logoId: 1, certExt: 'jpg', hasCert: true,
  },
  {
    id: 27, title: 'Tata – ESG Job Simulation', issuer: 'Forage',
    date: 'Jul 2025', category: 'Industry Sim',
    description: 'Tata Group ESG simulation covering Environmental, Social, and Governance frameworks — participants analyze sustainability metrics and develop responsible business recommendations.',
    credentialId: 'R4JnxBvZhHDX9EdBs',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/ifobHAoMjQs9s6bKS/N8Muuhk6XsXgMTeu2_ifobHAoMjQs9s6bKS_hcRBjkdaCuSnWEct3_1752986965182_completion_certificate.pdf',
    logoId: 27, certExt: 'jpg', hasCert: true,
  },
  {
    id: 28, title: 'AI Appreciate', issuer: 'Intel',
    date: 'Jul 2025', category: 'AI / ML',
    description: "Intel-backed foundational program introducing AI literacy, core machine learning principles, and Intel's AI technologies with a focus on industry impact and responsible AI.",
    logoId: 28, certExt: 'jpg', hasCert: true,
  },
  {
    id: 29, title: 'AI Appreciate Badge – AI For All', issuer: 'CBSE and Intel',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'CBSE and Intel recognition for foundational AI knowledge through the AI For All initiative — covering AI concepts, ML basics, and ethical implications of artificial intelligence.',
    credentialId: 'U2FsdGVkX19byxezeJda8rWW8BlykmTgRhYX8Fau7Oh4JqqNg5brK50f7xhpz0jR',
    url: 'https://ai-for-all.in/#/badge?id=U2FsdGVkX19byxezeJda8rWW8BlykmTgRhYX8Fau7Oh4JqqNg5brK50f7xhpz0jR',
    logoId: 28, certExt: 'jpg', hasCert: true,
  },
  {
    id: 30, title: 'Artificial Intelligence for All', issuer: 'Ministry of Education',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Ministry of Education AI awareness program introducing AI fundamentals, real-world applications, and digital literacy skills aligned with national AI education objectives.',
    logoId: 30, certExt: 'jpg', hasCert: true,
  },
  {
    id: 31, title: 'AI Aware Badge – AI For All', issuer: 'CBSE and Intel',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'AI awareness-level certification from the CBSE and Intel AI For All initiative covering AI definitions, applications, and responsible AI principles for digital citizenship.',
    url: 'https://ai-for-all.in/#/badge?id=U2FsdGVkX19egHgQNubs1L2a3S4hswjuLWPuw16PHu1p1L2u3Sp5Q4s1L2a3S4hOpypo2QfThIa12FAN1u5SwZ',
    logoId: 28, certExt: 'jpg', hasCert: true,
  },
  {
    id: 32, title: 'Training a New Model', issuer: 'Infosys Springboard',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Practical course on training ML models covering dataset preparation, model architecture selection, training loops, hyperparameter tuning, and performance evaluation.',
    logoId: 32, certExt: 'jpg', hasCert: true,
  },
  {
    id: 33, title: 'From Capture to Analysis – Object Detection with Python and TensorFlow', issuer: 'Infosys Springboard',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'End-to-end computer vision course on object detection using Python and TensorFlow — covering CNNs, YOLO architecture, model training, and deploying detection pipelines.',
    logoId: 32, certExt: 'jpg', hasCert: true,
  },
  {
    id: 34, title: 'AWS – Solutions Architecture Job Simulation', issuer: 'Forage',
    date: 'Jul 2025', category: 'Industry Sim',
    description: 'AWS-developed job simulation covering solutions architecture principles, cloud infrastructure design, and cost optimization by architecting real-world scalable AWS solutions.',
    credentialId: 'wWPnzaTfuxjg7QwxF',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/pmnMSL4QiQ9JCgE3W/kkE9HyeNcw6rwCRGw_pmnMSL4QiQ9JCgE3W_hcRBjkdaCuSnWEct3_1752419592521_completion_certificate.pdf',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 35, title: 'Understanding the Working of Neural Networks', issuer: 'Analytics Vidhya',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Conceptual and practical exploration of neural network architectures including feedforward, CNNs, and RNNs — covering backpropagation, activation functions, and model building.',
    url: 'https://courses.analyticsvidhya.com/certificates/xapvce4bbw',
    logoId: 1, certExt: 'jpg', hasCert: true,
  },
  {
    id: 36, title: 'Tata – GenAI Powered Data Analytics Job Simulation', issuer: 'Forage',
    date: 'Jul 2025', category: 'Industry Sim',
    description: 'Tata GenAI simulation exploring AI-augmented data analytics workflows — covering insight generation and presenting data-driven recommendations using generative AI tools.',
    credentialId: 'iFZAtoKKs6BfdojSq',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/ifobHAoMjQs9s6bKS/gMTdCXwDdLYoXZ3wG_ifobHAoMjQs9s6bKS_hcRBjkdaCuSnWEct3_1752309220580_completion_certificate.pdf',
    logoId: 27, certExt: 'jpg', hasCert: true,
  },
  {
    id: 37, title: 'Deloitte Australia – Technology Job Simulation', issuer: 'Forage',
    date: 'Jul 2025', category: 'Industry Sim',
    description: 'Deloitte Australia technology simulation covering digital transformation strategy, technical problem-solving, and client engagement as a technology consultant.',
    credentialId: 'oEQZqNEzPFuxr2wtz',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/9PBTqmSxAf6zZTseP/udmxiyHeqYQLkTPvf_9PBTqmSxAf6zZTseP_hcRBjkdaCuSnWEct3_1752308221732_completion_certificate.pdf',
    logoId: 27, certExt: 'jpg', hasCert: true,
  },
  {
    id: 38, title: 'Deloitte Australia – Cyber Job Simulation', issuer: 'Forage',
    date: 'Jul 2025', category: 'Industry Sim',
    description: 'Deloitte cybersecurity simulation covering threat assessment, incident response, vulnerability analysis, and remediation strategy using industry security frameworks.',
    credentialId: 'QGy9MQitqQk9wDoRh',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/9PBTqmSxAf6zZTseP/E9pA6qsdbeyEkp3ti_9PBTqmSxAf6zZTseP_hcRBjkdaCuSnWEct3_1752307665080_completion_certificate.pdf',
    logoId: 27, certExt: 'jpg', hasCert: true,
  },
  {
    id: 39, title: 'Deloitte Australia – Data Analytics Job Simulation', issuer: 'Forage',
    date: 'Jul 2025', category: 'Industry Sim',
    description: 'Deloitte data analytics simulation covering data cleaning, analysis, visualization, and delivering actionable business insights in a professional consulting engagement.',
    credentialId: 'tSNuYBzgQ68avAXSn',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/9PBTqmSxAf6zZTseP/io9DzWKe3PTsiS6GG_9PBTqmSxAf6zZTseP_hcRBjkdaCuSnWEct3_1752307221000_completion_certificate.pdf',
    logoId: 27, certExt: 'jpg', hasCert: true,
  },
  {
    id: 40, title: 'Fundamentals of Responsible AI', issuer: 'Infosys Springboard',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Explores responsible AI principles including fairness, transparency, accountability, bias detection, and frameworks for building trustworthy AI systems.',
    logoId: 40, certExt: 'jpg', hasCert: true,
  },
  {
    id: 41, title: 'Artificial Intelligence for All', issuer: 'Infosys Springboard',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Broad AI introduction covering machine learning basics, NLP, computer vision, and the transformative role of AI across industries for all learners.',
    logoId: 40, certExt: 'jpg', hasCert: true,
  },
  {
    id: 42, title: 'Generative AI for All', issuer: 'Infosys Springboard',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Accessible introduction to generative AI technologies including LLMs, diffusion models, prompt engineering, and the societal impact of generative models.',
    logoId: 40, certExt: 'jpg', hasCert: true,
  },
  {
    id: 43, title: 'Microsoft Applied Skills: Accelerate App Development by Using GitHub Copilot', issuer: 'Microsoft',
    date: 'Jul 2025', category: 'DevOps',
    description: 'Microsoft Applied Skills credential for using GitHub Copilot to accelerate development — covering code explanation, feature generation, unit testing, and performance/security refactoring.',
    credentialId: 'A53FC0314E3099D8',
    url: 'https://learn.microsoft.com/en-us/users/RishabhSharma-1100/credentials/A53FC0314E3099D8?ref=https%3a%2f%2fwww.linkedin.com%2f',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 44, title: 'Evaluate Generative AI Performance in Azure AI Foundry Portal', issuer: 'Microsoft',
    date: 'Jul 2025', category: 'AI / ML',
    description: 'Hands-on credential for evaluating generative AI model performance in Azure AI Foundry — covering evaluation metrics, safety assessments, and quality benchmarking.',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/achievements/4gx7asjk',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 45, title: 'SQL', issuer: 'OneRoadmap',
    date: 'Jun 2025', category: 'Data',
    description: 'Comprehensive SQL certification validating skills in database querying, joins, aggregations, subqueries, window functions, and relational database analysis.',
    url: 'https://www.oneroadmap.io/skills/sql/certificate/CERT-893DAD4F',
    logoId: 45, certExt: 'jpg', hasCert: true,
  },
  {
    id: 46, title: 'Python', issuer: 'OneRoadmap',
    date: 'Jun 2025', category: 'Web Dev',
    description: 'Python proficiency certification covering data structures, OOP, file I/O, libraries, and best practices for automation, data processing, and application development.',
    url: 'https://www.oneroadmap.io/skills/python/certificate/CERT-748E9ADE',
    logoId: 45, certExt: 'jpg', hasCert: true,
  },
  {
    id: 47, title: 'AI and Data Scientist', issuer: 'OneRoadmap',
    date: 'Jun 2025', category: 'AI / ML',
    description: 'Comprehensive AI and data science certification covering the full workflow from data preprocessing and feature engineering to model deployment and evaluation.',
    url: 'https://www.oneroadmap.io/skills/ai-ds/certificate/CERT-82A61AA7',
    logoId: 45, certExt: 'jpg', hasCert: false,
  },
  {
    id: 48, title: 'AI Engineer', issuer: 'OneRoadmap',
    date: 'Jun 2025', category: 'AI / ML',
    description: 'AI engineering certification validating skills in designing, building, and deploying AI systems, model optimization, API integration, and MLOps practices at scale.',
    url: 'https://www.oneroadmap.io/skills/ai/certificate/CERT-F5DB3790',
    logoId: 45, certExt: 'jpg', hasCert: true,
  },
  {
    id: 49, title: 'Data Analyst', issuer: 'OneRoadmap',
    date: 'Jun 2025', category: 'Data',
    description: 'Core data analyst certification covering data cleaning, statistical analysis, visualization, and transforming raw data into actionable business insights.',
    url: 'https://www.oneroadmap.io/skills/da/certificate/CERT-02F57120',
    logoId: 45, certExt: 'jpg', hasCert: true,
  },
  {
    id: 50, title: 'Microsoft Applied Skills: Build a Natural Language Processing Solution with Azure AI Language', issuer: 'Microsoft',
    date: 'Jun 2025', category: 'AI / ML',
    description: 'Applied credential for building NLP solutions with Azure AI Language — covering text analytics, sentiment analysis, entity recognition, and conversational AI deployment.',
    credentialId: '5A727031AAFD46C8',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/credentials/5a727031aafd46c8?ref=https%3A%2F%2Fwww.linkedin.com%2F',
    logoId: 50, certExt: 'png', hasCert: true,
  },
  {
    id: 51, title: 'Reinforcement Finetuning LLMs with GRPO', issuer: 'DeepLearning.AI',
    date: 'May 2025', category: 'AI / ML',
    description: 'Advanced course on fine-tuning LLMs using Group Relative Policy Optimization (GRPO) — covering reward modeling, policy gradient methods, and aligning models to specific objectives.',
    url: 'https://learn.deeplearning.ai/accomplishments/e28d8235-cd5f-4039-8a67-a27c89327eca?usp=sharing',
    logoId: 51, certExt: 'png', hasCert: true,
  },
  {
    id: 52, title: 'DSPy: Build and Optimize Agentic Apps', issuer: 'DeepLearning.AI',
    date: 'May 2025', category: 'AI / ML',
    description: 'Hands-on DSPy framework training for building and optimizing LLM-powered agentic applications — covering modules, teleprompters, signatures, and automated prompt optimization.',
    url: 'https://learn.deeplearning.ai/accomplishments/e207019b-e781-4fd4-b9be-0cd2558b6498?usp=sharing',
    logoId: 51, certExt: 'png', hasCert: true,
  },
  {
    id: 53, title: 'Accenture UK – Developer and Technology Job Simulation', issuer: 'Accenture',
    date: 'May 2025', category: 'Industry Sim',
    description: 'Accenture UK technology simulation covering software development workflows, architecture analysis, and technical problem-solving as a technology consultant.',
    credentialId: 'nqM7wzzErnPEjdSBX',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/ovyvuqqNRQKBjNxbj/3xnZEj9kfpoQKW885_ovyvuqqNRQKBjNxbj_hcRBjkdaCuSnWEct3_1748234353332_completion_certificate.pdf',
    logoId: 53, certExt: 'jpg', hasCert: true,
  },
  {
    id: 54, title: 'Develop a Vision-Enabled Generative AI Application', issuer: 'Microsoft',
    date: 'May 2025', category: 'AI / ML',
    description: 'Applied credential for building vision-enabled generative AI applications using Azure AI services — covering image analysis, multimodal models, and Azure OpenAI integration.',
    url: 'https://learn.microsoft.com/en-us/users/RishabhSharma-1100/achievements/JU8KCMET?ref=https%3a%2f%2fwww.linkedin.com%2f',
    logoId: 50, certExt: 'png', hasCert: true,
  },
  {
    id: 55, title: 'Develop an Audio-Enabled Generative AI Application', issuer: 'Microsoft',
    date: 'May 2025', category: 'AI / ML',
    description: 'Applied credential for developing audio-enabled generative AI applications using Azure AI Speech — covering speech-to-text, TTS, audio understanding, and voice-enabled AI deployment.',
    url: 'https://learn.microsoft.com/en-us/users/RishabhSharma-1100/achievements/74YQDNKZ?ref=https%3a%2f%2fwww.linkedin.com%2f',
    logoId: 50, certExt: 'png', hasCert: true,
  },
  {
    id: 56, title: 'Develop Natural Language Processing Solutions with Azure AI Services', issuer: 'Microsoft',
    date: 'May 2025', category: 'AI / ML',
    description: 'Validates skills in building production NLP solutions with Azure AI Services including text analytics, custom classification, entity recognition, and language understanding pipelines.',
    credentialId: 'EA323091DE1817A6',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/achievements/74yqdnkz?ref=https%3A%2F%2Fwww.linkedin.com%2F',
    logoId: 50, certExt: 'png', hasCert: true,
  },
  {
    id: 57, title: 'Tata Group – Data Visualisation: Empowering Business with Effective Insights Job Simulation', issuer: 'Forage',
    date: 'May 2025', category: 'Industry Sim',
    description: 'Tata Group simulation focused on data visualization and business storytelling — creating compelling visual narratives from complex datasets for executive decision-making.',
    credentialId: 'GkyjND85yhJzszp3p',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/ifobHAoMjQs9s6bKS/MyXvBcppsW2FkNYCX_ifobHAoMjQs9s6bKS_hcRBjkdaCuSnWEct3_1748073367955_completion_certificate.pdf',
    logoId: 27, certExt: 'jpg', hasCert: true,
  },
  {
    id: 58, title: 'Large Language Models', issuer: 'Hugging Face',
    date: 'May 2025', category: 'AI / ML',
    description: 'Comprehensive LLM coverage using Hugging Face — including transformer architectures, tokenization, fine-tuning workflows, and deploying NLP models with the Hugging Face ecosystem.',
    logoId: 58, certExt: 'jpg', hasCert: true,
  },
  {
    id: 59, title: 'Generative AI with Diffusion Models', issuer: 'Amazon Web Services (AWS)',
    date: 'May 2025', category: 'AI / ML',
    description: 'Deep dive into diffusion model architectures for image generation on AWS — covering Stable Diffusion fundamentals, noise scheduling, and deploying diffusion-based generative AI at scale.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 60, title: 'Building Language Models on AWS', issuer: 'Amazon Web Services (AWS)',
    date: 'May 2025', category: 'AI / ML',
    description: 'Hands-on training for building and deploying language models on AWS using SageMaker and Bedrock — covering data preprocessing, distributed training, and LLM deployment strategies.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 61, title: 'Customizing and Evaluating LLMs Using Amazon SageMaker', issuer: 'Amazon Web Services (AWS)',
    date: 'May 2025', category: 'AI / ML',
    description: 'Advanced course on fine-tuning and evaluating LLMs with Amazon SageMaker — covering PEFT techniques, evaluation pipelines, A/B testing, and optimizing LLM performance.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 62, title: 'Amazon SageMaker JumpStart Foundations', issuer: 'Amazon Web Services (AWS)',
    date: 'May 2025', category: 'Cloud',
    description: 'Introduction to Amazon SageMaker JumpStart for rapid deployment of pre-built and foundation models — covering the model hub, one-click deployment, and fine-tuning strategies.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 63, title: 'Foundations of Prompt Engineering', issuer: 'Amazon Web Services (AWS)',
    date: 'May 2025', category: 'AI / ML',
    description: 'Foundational prompt engineering certification covering zero-shot, few-shot, chain-of-thought techniques, and designing effective prompts for AWS AI services.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 64, title: 'AWS Technical Essentials', issuer: 'Amazon Web Services (AWS)',
    date: 'May 2025', category: 'Cloud',
    description: 'Foundational AWS technical training covering core services including EC2, S3, VPC, IAM, RDS, and Lambda with hands-on experience building scalable cloud applications.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 65, title: 'Applying AI Principles with Google Cloud', issuer: 'Google',
    date: 'May 2025', category: 'AI / ML',
    description: 'Training on responsible AI principles and their practical application in Google Cloud — covering fairness, interpretability, privacy, and ethical AI development.',
    logoId: 2, certExt: 'jpg', hasCert: true,
  },
  {
    id: 66, title: 'Prompt Design in Vertex AI', issuer: 'Google',
    date: 'May 2025', category: 'AI / ML',
    description: 'Certification in effective prompt design for Vertex AI generative models — covering zero-shot, few-shot, and instruction-based prompting for text, code, and multimodal tasks.',
    url: 'https://www.credly.com/badges/146e4ae9-e7a8-42a7-a733-3da53268cb78/public_url',
    logoId: 2, certExt: 'jpg', hasCert: true,
  },
  {
    id: 67, title: 'Introduction to Responsible AI', issuer: 'Google',
    date: 'May 2025', category: 'AI / ML',
    description: "Google's foundational responsible AI course covering fairness, accountability, transparency, bias detection, and ethical decision-making frameworks in AI development.",
    url: 'https://www.cloudskillsboost.google/paths/118/course_templates/554/badge',
    logoId: 2, certExt: 'jpg', hasCert: true,
  },
  {
    id: 68, title: 'Introduction to Large Language Models', issuer: 'Google',
    date: 'May 2025', category: 'AI / ML',
    description: 'Overview of large language model architectures, capabilities, and applications in Google Cloud — covering transformer fundamentals, fine-tuning approaches, and practical LLM use cases.',
    logoId: 2, certExt: 'jpg', hasCert: true,
  },
  {
    id: 69, title: 'Introduction to Generative AI', issuer: 'Google',
    date: 'May 2025', category: 'AI / ML',
    description: "Foundational introduction to generative AI concepts, use cases, and Google's generative AI tools — covering how generative models work and getting started with Google AI.",
    logoId: 2, certExt: 'jpg', hasCert: true,
  },
  {
    id: 70, title: 'AWS Cloud Practitioner Essentials', issuer: 'Amazon Web Services (AWS)',
    date: 'May 2025', category: 'Cloud',
    description: "Comprehensive AWS cloud fundamentals preparation covering core services, the Well-Architected Framework's six pillars, billing, and security best practices.",
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 71, title: 'GitHub Professional Certificate', issuer: 'LinkedIn',
    date: 'Mar 2025', category: 'DevOps',
    description: 'Professional GitHub certification covering version control, collaboration, CI/CD workflows, GitHub Actions, repository management, and open-source contribution best practices.',
    url: 'https://www.linkedin.com/learning/certificates/c3bbee25df46a75c10c78463bfa1c51ed6dd6173e42bcec607ea58f6f3328cfd',
    logoId: 71, certExt: 'jpg', hasCert: true,
  },
  {
    id: 72, title: 'Multi AI Agents and Advanced Use Cases', issuer: 'DeepLearning.AI',
    date: 'Mar 2025', category: 'AI / ML',
    description: 'Advanced training on building multi-agent AI systems for complex collaborative task completion — covering agent orchestration, tool use, and deploying sophisticated agentic workflows.',
    url: 'https://learn.deeplearning.ai/accomplishments/38e8c8f7-dae1-49dc-8e6b-a0cd60daae8c?usp=sharing',
    logoId: 51, certExt: 'png', hasCert: true,
  },
  {
    id: 73, title: 'Career Essentials in Data Analysis by Microsoft and LinkedIn', issuer: 'Microsoft',
    date: 'Mar 2025', category: 'Data',
    description: 'Joint Microsoft and LinkedIn certification covering Excel, Power BI, statistical thinking, and data storytelling to build a professional data analysis foundation.',
    url: 'https://www.linkedin.com/learning/certificates/2f0827ae29a800554bafa212bd710ff28b17d61688a59db46d954136b4761196',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 74, title: 'Deep Data Analytics', issuer: 'National Association of State Boards of Accountancy (NASBA)',
    date: 'Mar 2025', category: 'Data',
    description: 'Advanced data analytics program covering statistical modeling, predictive analytics, and decision intelligence frameworks for strategic data-driven business planning.',
    url: 'https://www.linkedin.com/learning/certificates/c41737526aae41ba1886135c9fbfaa556e4df3846d35150272aca1523cbfb9d1',
    logoId: 74, certExt: 'jpg', hasCert: true,
  },
  {
    id: 75, title: 'Advanced Data Analytics', issuer: 'LinkedIn',
    date: 'Mar 2025', category: 'Data',
    description: 'Advanced data analytics certification covering sophisticated statistical methods, predictive modeling, and applying advanced analytics for strategic business insights.',
    url: 'https://www.linkedin.com/learning/certificates/7e5b256e2de5a3a890e325c9bec8e0274da29a6890bd166b754328b23698549e',
    logoId: 71, certExt: 'jpg', hasCert: true,
  },
  {
    id: 76, title: 'Data Analytics', issuer: 'LinkedIn',
    date: 'Mar 2025', category: 'Data',
    description: 'Comprehensive data analytics certification covering foundational to intermediate skills in data analysis, visualization, and communicating insights with industry-standard tools.',
    logoId: 71, certExt: 'jpg', hasCert: true,
  },
  {
    id: 77, title: 'Learning Data Analytics', issuer: 'National Association of State Boards of Accountancy (NASBA)',
    date: 'Mar 2025', category: 'Data',
    description: 'Structured learning program introducing core data analytics concepts, tools, and methodologies through practical applications and visual communication of findings.',
    logoId: 74, certExt: 'jpg', hasCert: true,
  },
  {
    id: 78, title: 'Career Skills in Data Analytics', issuer: 'LinkedIn',
    date: 'Jan 2025', category: 'Data',
    description: 'Career-focused data analytics certification developing practical skills in data storytelling, visualization, and applying data-driven decision-making in professional contexts.',
    logoId: 71, certExt: 'jpg', hasCert: true,
  },
  {
    id: 79, title: 'Complete Generative AI Course with LangChain and Hugging Face', issuer: 'Udemy',
    date: 'Mar 2025', category: 'AI / ML',
    description: 'Comprehensive Udemy course on generative AI development using LangChain and Hugging Face — covering RAG pipelines, agent building, fine-tuning, and deploying production LLM applications.',
    logoId: 79, certExt: 'jpg', hasCert: true,
  },
  {
    id: 80, title: 'Multi AI Agent System', issuer: 'DeepLearning.AI',
    date: 'Mar 2025', category: 'AI / ML',
    description: 'Specialized training on multi-agent AI systems using CrewAI — covering agent roles, task decomposition, collaborative AI system design, and enterprise deployment.',
    url: 'https://learn.deeplearning.ai/accomplishments/3788066a-799c-4a8d-b111-fc0aba690a8d?usp=sharing',
    logoId: 51, certExt: 'png', hasCert: true,
  },
  {
    id: 81, title: 'Computer Vision Solutions with Azure AI Vision', issuer: 'Microsoft AI',
    date: 'Mar 2025', category: 'AI / ML',
    description: 'Hands-on credential for building computer vision solutions with Azure AI Vision — covering image classification, object detection, OCR, and deploying production vision AI on Azure.',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/achievements/zkr8pe72',
    logoId: 81, certExt: 'jpg', hasCert: true,
  },
  {
    id: 82, title: 'Vision Models with Azure AI Custom Vision', issuer: 'Microsoft',
    date: 'Mar 2025', category: 'AI / ML',
    description: 'Applied credential for training custom image classification and object detection models with Azure AI Custom Vision — covering dataset preparation, training, and model deployment.',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/achievements/wz3lrfrn',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 83, title: 'AI Agents', issuer: 'NiCE Cognigy',
    date: 'Mar 2025', category: 'AI / ML',
    description: "NiCE Cognigy AI Agents certification covering NLU, dialog management, agent orchestration, and building intelligent automation workflows for enterprise customer engagement.",
    url: 'https://academy.cognigy.com/certificates/pkiij3xkda',
    logoId: 83, certExt: 'jpg', hasCert: true,
  },
  {
    id: 84, title: 'Develop Natural Language Processing Solutions with Azure AI Services', issuer: 'Microsoft AI',
    date: 'Mar 2025', category: 'AI / ML',
    description: 'Validates skills in developing end-to-end NLP solutions with Azure AI Services — covering text analysis, conversational AI, question answering, and language application deployment.',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/achievements/74yqdnkz?ref=https%3A%2F%2Fwww.linkedin.com%2F',
    logoId: 81, certExt: 'png', hasCert: true,
  },
  {
    id: 85, title: 'Complete Data Science, Machine Learning, Deep Learning, NLP Bootcamp', issuer: 'Udemy',
    date: 'Feb 2025', category: 'AI / ML',
    description: 'Comprehensive bootcamp covering the full data science spectrum from statistics to deep learning and NLP — validating end-to-end ML model building and deployment skills.',
    logoId: 79, certExt: 'jpg', hasCert: true,
  },
  {
    id: 86, title: 'Deploy Applications with Azure DevOps', issuer: 'Microsoft',
    date: 'Nov 2024', category: 'DevOps',
    description: 'Credential for deploying applications with Azure DevOps — covering YAML pipelines, release management, deployment strategies, and artifact management for continuous delivery.',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/achievements/cfah63m9?ref=https%3A%2F%2Fwww.linkedin.com%2F',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 87, title: 'Host Your Own Build Agent in Azure Pipelines', issuer: 'Microsoft',
    date: 'Nov 2024', category: 'DevOps',
    description: 'Technical credential for configuring self-hosted build agents in Azure Pipelines — covering agent pool setup, security configuration, and custom build environment management.',
    url: 'https://learn.microsoft.com/en-us/users/RishabhSharma-1100/achievements/UY75HMD3?ref=https%3a%2f%2fwww.linkedin.com%2f',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 88, title: 'Explore Azure DevOps with GitHub to Streamline Your Development Process', issuer: 'Microsoft',
    date: 'Nov 2024', category: 'DevOps',
    description: 'Credential for integrating Azure DevOps with GitHub — covering GitHub Actions, Azure Boards, CI/CD integration, and streamlining DevOps practices across the Microsoft developer ecosystem.',
    url: 'https://learn.microsoft.com/en-us/users/rishabhsharma-1100/achievements/fve9f72x?ref=https%3A%2F%2Fwww.linkedin.com%2F',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 89, title: 'AZ-400: Development for Enterprise DevOps', issuer: 'Microsoft',
    date: 'Nov 2024', category: 'DevOps',
    description: 'Advanced AZ-400 aligned credential covering DevOps transformation, CI/CD pipelines, infrastructure as code, and secure automated software delivery on Azure.',
    url: 'https://learn.microsoft.com/api/achievements/share/en-us/RishabhSharma-1100/HA2TR2W8?sharingId=EA323091DE1817A6',
    logoId: 43, certExt: 'jpg', hasCert: true,
  },
  {
    id: 90, title: 'Gen AI for Software Development', issuer: 'IBM',
    date: 'Oct 2024', category: 'AI / ML',
    description: 'IBM course on applying generative AI to software development workflows — covering code generation, AI-assisted testing, documentation, and developer productivity tools.',
    logoId: 8, certExt: 'jpg', hasCert: true,
  },
  {
    id: 91, title: 'Text to Speech Using IBM watsonx', issuer: 'IBM',
    date: 'Oct 2024', category: 'AI / ML',
    description: 'Practical credential for building text-to-speech applications with IBM watsonx — covering voice customization, neural TTS models, and deploying natural-sounding speech synthesis.',
    logoId: 8, certExt: 'jpg', hasCert: true,
  },
  {
    id: 92, title: 'Prompt Engineering with Azure OpenAI', issuer: 'Microsoft',
    date: 'Sep 2024', category: 'AI / ML',
    description: 'Credential for designing effective prompts for Azure OpenAI models — covering prompt patterns, few-shot learning, parameter tuning, and building production generative AI applications.',
    credentialId: 'EA323091DE1817A6',
    url: 'https://learn.microsoft.com/api/achievements/share/en-us/RishabhSharma-1100/QT4JR5WE?sharingId=EA323091DE1817A6',
    logoId: 43, certExt: 'png', hasCert: true,
  },
  {
    id: 93, title: 'APIs and RESTful APIs Crash Course', issuer: 'Udemy',
    date: 'Mar 2024', category: 'Web Dev',
    description: 'Comprehensive introduction to API design, RESTful architecture, HTTP methods, authentication patterns, and real-world REST API development and consumption.',
    logoId: 79, certExt: 'jpg', hasCert: true,
  },
  {
    id: 94, title: 'Accenture North America – Data Analytics and Visualization Job Simulation', issuer: 'Accenture',
    date: 'Sep 2024', category: 'Industry Sim',
    description: 'Accenture data analytics simulation covering data cleaning, visualization, and delivering data-driven recommendations in a professional consulting engagement context.',
    credentialId: 'hs3YjSiBD9k7g8EjW',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/Accenture%20North%20America/hzmoNKtzvAzXsEqx8_Accenture%20North%20America_hcRBjkdaCuSnWEct3_1726409854488_completion_certificate.pdf',
    logoId: 53, certExt: 'jpg', hasCert: true,
  },
  {
    id: 95, title: 'JPMorgan Chase & Co. – Excel Skills Job Simulation', issuer: 'Forage',
    date: 'Sep 2024', category: 'Industry Sim',
    description: 'JPMorgan Chase Excel simulation covering advanced spreadsheet skills, financial modeling, VBA, pivot tables, and statistical functions for real-world financial analysis.',
    credentialId: 'r4vqRNjx254aku78z',
    url: 'https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/JPMorgan%20Chase%20Corporate/XiuvjcwqWRqH9oy38_JPMorgan%20Chase%20%26%20Co._hcRBjkdaCuSnWEct3_1726403438797_completion_certificate.pdf',
    logoId: 27, certExt: 'jpg', hasCert: true,
  },
  {
    id: 96, title: 'Building a Machine Learning Ready Organisation', issuer: 'Amazon Web Services (AWS)',
    date: 'Sep 2024', category: 'AI / ML',
    description: 'Strategic course on preparing organizations for ML adoption — covering data culture, infrastructure planning, team structure, and governance frameworks for successful AI implementation.',
    logoId: 13, certExt: 'jpg', hasCert: true,
  },
  {
    id: 97, title: 'Java Servlet and JSP', issuer: 'SkillUp Online',
    date: 'Dec 2023', category: 'Web Dev',
    description: 'Java web development certification covering Servlets and JSP for building dynamic server-side applications with session management, JSTL, and MVC architecture.',
    logoId: 97, certExt: 'jpg', hasCert: true,
  },
  {
    id: 98, title: 'MERN Stack Programming', issuer: 'SkillUp Online',
    date: 'Dec 2023', category: 'Web Dev',
    description: 'Full-stack web development certification covering MongoDB, Express.js, React, and Node.js for building complete, scalable web applications with a modern JavaScript stack.',
    logoId: 97, certExt: 'jpg', hasCert: true,
  },
  {
    id: 99, title: 'JavaScript Programming', issuer: 'SkillUp Online',
    date: 'Dec 2023', category: 'Web Dev',
    description: 'Comprehensive JavaScript certification covering language fundamentals, ES6+ features, DOM manipulation, async programming, and modern JS patterns for web development.',
    logoId: 97, certExt: 'jpg', hasCert: true,
  },
  {
    id: 100, title: 'Artificial Intelligence', issuer: 'LinkedIn',
    date: 'Feb 2024', category: 'AI / ML',
    description: "LinkedIn's foundational AI certification covering machine learning concepts, neural networks, AI applications, and practical AI skills for professional career development.",
    logoId: 71, certExt: 'jpg', hasCert: true,
  },
  {
    id: 101, title: '100 Days Python Bootcamp', issuer: 'Udemy',
    date: 'Mar 2024', category: 'Web Dev',
    description: 'Intensive 100-day Python bootcamp covering beginner to advanced topics including automation, data science, and web development through daily coding projects.',
    logoId: 79, certExt: 'jpg', hasCert: true,
  },
];
